### ISSUE TITLE
Убрать пустую строку.

### ISSUE THREAD

**Issue by Hibin** [besrezen90/besrezen90.github.io#7]
https://github.com/besrezen90/besrezen90.github.io/blob/b426b6bc01d25045193214da5b2066fcec80c7e2/js/solution.js#L196

Аналогично по всему коду, не нужно лишних пустых строк после открывайющей фигурной скобки/перед закрывающй и подобное. Чтобы не ломать восприятие.

**Comment by besrezen90** [comment]
Устранил
