### ISSUE TITLE
Убрать

### ISSUE THREAD

**Issue by Hibin** [besrezen90/besrezen90.github.io#9]
https://github.com/besrezen90/besrezen90.github.io/blob/b426b6bc01d25045193214da5b2066fcec80c7e2/js/solution.js#L585-L593

Закомментированный код, если он уже не нужен (код отлажен и работает), стоит убрать. В любом случае он уже сохранен в репозитории.

**Comment by Hibin** [comment]
Аналогично по всему коду.

**Comment by besrezen90** [comment]
Устранил
